name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install SFML lib
      run: sudo apt-get install libsfml-dev

    - name: Run Testes
      run:  make tests
